//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string Name { get; set; }
        public string Platform { get; set; }
        public string Language { get; set; }
        public Nullable<bool> Owned { get; set; }
        public Nullable<bool> Cartridge { get; set; }
        public Nullable<bool> Box { get; set; }
        public Nullable<bool> Manual { get; set; }
        public Nullable<bool> Guide { get; set; }
        public string Accessory { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> NewInBox { get; set; }
    }
}
